import initChangeJsToDataAttr from './modules/class-to-dataset.js';
import initScrollSuave from './modules/scroll-smooth.js';
import initAnimacaoScroll from './modules/scroll-animation.js';
import initAccordion from './modules/accordion-list.js';
import initTabNav from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdown from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initFetchAnimals from './modules/fetch-animals.js';

initChangeJsToDataAttr();
initScrollSuave();
initAnimacaoScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropdown();
initMenuMobile();
initFuncionamento();
initFetchAnimals();